### PR TITLE
Changes to support s390x Arch 

### PR DESCRIPTION
**Pull request by raja-sekhar-r**
Hi Team, .

Kindly review these changes, 

Thanks
Raja
CC/FYI - @chuckbrant, @arewm

### CODE REVIEW

**Comment by arewm** [comment]
Thanks for this PR, but I am not sure that this will work since we do not have anything but x86 builders in PROW. @ray-harris can confirm.

**Comment by ray-harris** [comment]
I'll check with the OpenShift CI squad, but I don't think we can build these in Prow yet.

**Comment by ray-harris** [comment]
Just to note:

The changes to the shell scripts don't break existing builds.

I'm able to build the go1.16-linux-s390x image on my mac using docker buildx build:

```
docker buildx build --platform linux/s390x -f Dockerfile.go1.16-linux-s390x -t builder:go1.15-linux-s390x .
```

**Comment by ray-harris** [comment]
Sorry. Accidentally clicked "Close with comment" instead of "Comment".

**Comment by ray-harris** [comment]
@raja-sekhar-r @arewm The Prow squad said the Dockerfile would build, but the architecture metadata in the resulting image would be wrong.

Also after talking with Andrew, we only need the s390x images in our downstream builds, not the upstream builds, but we need to use the same Dockerfile for each architecture to be able to generate a multiarch image in the downstream.

The only remaining difference is setting the GOARCH variable before downloading the Go tarball. I'll change this from an env var in the Dockerfile to a `uname -m` command in the setup-go.sh script. The Dockerfiles will be the same for amd64 and s390x at that point.

So what I'm going to do is:
- accept this PR to get the changes needed to the build/setup-* scripts for s390x
- update the setup-go.sh script and Dockerfiles to use `uname -m` instead of $GOARCH
- rename the `-linux-amd64` Dockerfiles to just `-linux`
- remove the `-linux-s390x`

I won't build the s390x images in the upstream, but this will get us ready to build a multi-architecture image in the downstream from these Dockerfiles.

Let me know what you think.

**Comment by raja-sekhar-r** [comment]
> @raja-sekhar-r @arewm The Prow squad said the Dockerfile would build, but the architecture metadata in the resulting image would be wrong.
> 
> Also after talking with Andrew, we only need the s390x images in our downstream builds, not the upstream builds, but we need to use the same Dockerfile for each architecture to be able to generate a multiarch image in the downstream.
> 
> The only remaining difference is setting the GOARCH variable before downloading the Go tarball. I'll change this from an env var in the Dockerfile to a `uname -m` command in the setup-go.sh script. The Dockerfiles will be the same for amd64 and s390x at that point.
> 
> So what I'm going to do is:
> 
> * accept this PR to get the changes needed to the build/setup-* scripts for s390x
> * update the setup-go.sh script and Dockerfiles to use `uname -m` instead of $GOARCH
> * rename the `-linux-amd64` Dockerfiles to just `-linux`
> * remove the `-linux-s390x`
> 
> I won't build the s390x images in the upstream, but this will get us ready to build a multi-architecture image in the downstream from these Dockerfiles.
> 
> Let me know what you think.

Agreed ... becomes lot simpler ...

**Pull request merged**
